# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=10, verbose_name='主题'),
        ),
    ]
