# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_auto_20171011_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add time'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add time'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Topic'),
        ),
    ]
